import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { ArrowRight, ArrowUp, ArrowUpRight, Check, ChevronDown, Database, GitBranch, LoaderCircle, Network, ShieldCheck, Sparkles, Terminal, X } from 'lucide-react'
import { api, useApi } from './api'
import type { CopilotAnswer, Node } from './api'
import { PageHeading } from './components'

interface Exchange { question: string; answer: CopilotAnswer }
export function CopilotPage() {
  const [url, setUrl] = useSearchParams()
  const context = url.get('gid')
  const [input, setInput] = useState(url.get('question') ?? '')
  const [history, setHistory] = useState<Exchange[]>([])
  const [pendingQuestion, setPendingQuestion] = useState('')
  const bottom = useRef<HTMLDivElement>(null)
  const topNodes = useApi<Node[]>('/top-nodes?limit=1')
  const exampleGid = context ?? topNodes.data?.[0]?.gid
  const suggestions = [
    { icon: GitBranch, title: 'Кто собирает деньги?', question: 'Какие узлы собирают деньги от многих отправителей?' },
    { icon: Sparkles, title: 'Объяснить приоритет', question: exampleGid !== undefined ? `Почему gid ${exampleGid} находится в топе?` : 'Каких клиентов смотреть первыми?' },
    { icon: Network, title: 'Найти транзитные узлы', question: 'Какие узлы похожи на транзитные?' },
    { icon: Database, title: 'Проверить гипотезу', question: exampleGid !== undefined ? `Каких данных не хватает для проверки gid ${exampleGid}?` : 'Каких данных не хватает для проверки гипотезы?' },
  ]
  const mutation = useMutation({ mutationFn: (message: string) => api<CopilotAnswer>('/copilot', { method: 'POST', body: JSON.stringify({ message, ...(context ? { context_gid: context } : {}) }) }), onSuccess: (answer, question) => { setHistory(h => [...h, { question, answer }]); setPendingQuestion(''); setInput('') }, onError: () => setPendingQuestion('') })
  const submit = (value = input) => { const text = value.trim(); if (text && !mutation.isPending) { setPendingQuestion(text); mutation.mutate(text) } }
  useEffect(() => { if (history.length || pendingQuestion) bottom.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }) }, [history.length, pendingQuestion])
  return <><PageHeading eyebrow="ОБЪЯСНИМЫЙ АНАЛИТИЧЕСКИЙ ПОМОЩНИК" title="AML Copilot" description="Задавайте вопросы о связях и проверяйте гипотезы на конкретных наблюдениях."><span className="local-mode"><i />Локальный режим · без API-ключа</span></PageHeading>
    <div className="copilot-layout"><section className="chat-panel"><div className="chat-top"><span><Sparkles size={16} />Исследование данных</span><span><ShieldCheck size={13} />В пределах текущего графа</span></div><div className="chat-content">{!history.length && !mutation.isPending ? <div className="chat-welcome"><span className="copilot-orb"><Sparkles size={30} strokeWidth={1.5} /></span><div className="eyebrow">ХОРОШЕЕ ИССЛЕДОВАНИЕ НАЧИНАЕТСЯ С ВОПРОСА</div><h2>Какую связь изучим?</h2><p>Я использую рассчитанные показатели и безопасные инструменты.<br />Наблюдения, гипотезы и ограничения всегда показаны отдельно.</p><div className="suggestions">{suggestions.map(item => <button key={item.title} disabled={mutation.isPending} onClick={() => submit(item.question)}><item.icon size={19} /><strong>{item.title}</strong><span>{item.question}</span><ArrowUpRight size={14} /></button>)}</div></div> : history.map((exchange, index) => <div key={index} className="chat-exchange"><div className="user-message"><span className="user-avatar">ВЫ</span><p>{exchange.question}</p></div><Answer answer={exchange.answer} /></div>)}
      {mutation.isPending && <><div className="user-message"><span className="user-avatar">ВЫ</span><p>{pendingQuestion}</p></div><div className="assistant-thinking"><LoaderCircle size={17} className="spin" />Проверяю доступные показатели и связи…</div></>}{mutation.error && <div className="chat-error">{mutation.error.message}<button onClick={() => submit()}>Повторить</button></div>}<div ref={bottom} /></div>
      <div className="composer-wrap">{context && <div className="context-chip"><Network size={13} />Контекст: gid {context}<button title="Убрать контекст" onClick={() => setUrl({})}><X size={12} /></button></div>}<form className="chat-composer" onSubmit={event => { event.preventDefault(); submit() }}><textarea aria-label="Вопрос AML Copilot" placeholder={exampleGid !== undefined ? `Например: куда дальше уходят деньги от gid ${exampleGid}?` : 'Задайте вопрос о клиентах, кластерах или движении средств…'} maxLength={2000} value={input} rows={2} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} /><button aria-label="Отправить вопрос" disabled={!input.trim() || mutation.isPending}><ArrowUp size={20} /></button></form><div className="composer-note"><span>Enter — отправить · Shift + Enter — новая строка</span><span>{input.length}/2000</span></div></div>
    </section><aside className="copilot-sidebar"><div className="eyebrow">АНАЛИТИК ОСТАЁТСЯ В КОНТРОЛЕ</div><h3>Ответ можно проверить</h3><div className="copilot-principles"><div><Check size={16} /><span><strong>Наблюдения</strong>Фактические числа и конкретные gid из текущего расчёта.</span></div><div><GitBranch size={16} /><span><strong>Гипотезы</strong>Возможное объяснение структуры, требующее дополнительной проверки.</span></div><div><ShieldCheck size={16} /><span><strong>Границы знания</strong>Неполное наблюдение и данные, необходимые для следующего шага.</span></div></div><div className="copilot-tools-note"><Terminal size={20} /><h4>Инструменты вместо догадок</h4><p>Для каждого ответа доступен список вызванных инструментов и их параметров.</p><Link to="/methodology">Открыть методологию<ArrowRight size={13} /></Link></div><div className="copilot-context"><span className="status-dot" /><span>Внешние модели и передача данных не используются.</span></div></aside></div>
  </>
}
function Answer({ answer }: { answer: CopilotAnswer }) {
  return <div className="assistant-message"><span className="assistant-avatar"><Sparkles size={16} /></span><div className="answer-body"><div className="answer-heading"><strong>AML Copilot</strong><span>Локальная аналитика</span></div><p className="answer-text">{answer.answer}</p>{answer.observations.length > 0 && <section className="answer-section"><h4><span className="answer-dot observation" />Наблюдения</h4><ul>{answer.observations.map((text, i) => <li key={i}>{text}</li>)}</ul></section>}{answer.hypotheses.length > 0 && <section className="answer-section"><h4><span className="answer-dot hypothesis-dot" />Гипотезы для проверки</h4><ul>{answer.hypotheses.map((text, i) => <li key={i}>{text}</li>)}</ul></section>}{answer.limitations.length > 0 && <section className="answer-section limitation-section"><h4>Ограничения наблюдения</h4><ul>{answer.limitations.map((text, i) => <li key={i}>{text}</li>)}</ul></section>}<div className="answer-links">{answer.links.map((link, i) => <div className="answer-entity" key={`${link.type}-${link.id}-${i}`}><Link to={link.type === 'node' ? `/nodes/${link.id}` : `/clusters/${link.id}`}>{link.label}<ArrowUpRight size={13} /></Link>{link.type === 'node' && <Link title="Открыть на графе" to={`/graph?gid=${link.id}`}><Network size={14} /></Link>}</div>)}</div><details className="tools-details"><summary><Database size={13} />Использованные инструменты · {answer.tools_used.length}<ChevronDown size={13} /></summary><div>{answer.tools_used.map((tool, i) => <div className="tool-record" key={i}><code>{tool.name}</code><pre>{JSON.stringify(tool.parameters, null, 2)}</pre><p>{tool.summary}</p></div>)}</div></details></div></div>
}

