import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { createColumnHelper, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import type { SortingState } from '@tanstack/react-table'
import { ArrowDown, ArrowDownLeft, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, ArrowUpDown, BookOpen, ChevronLeft, ChevronRight, CircleHelp, Clock3, GitBranch, Network, Search, ShieldAlert, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { metric, money, num, params, pct, roles, useApi } from './api'
import type { Cluster, Graph, Methodology, Node } from './api'
import { ExportButton, GraphCanvas, NodeLink, PageHeading, Panel, RoleBadge, Score, State } from './components'

const column = createColumnHelper<Node>()
export function PrioritiesPage() {
  const [url, setUrl] = useSearchParams()
  const [q, setQ] = useState(url.get('q') ?? '')
  const [role, setRole] = useState(url.get('role') ?? '')
  const [cluster, setCluster] = useState(url.get('cluster_id') ?? '')
  const [seed, setSeed] = useState('')
  const [page, setPage] = useState(1)
  const [sorting, setSorting] = useState<SortingState>([{ id: 'priority_score', desc: true }])
  const search = url.get('q') ?? ''
  const clusters = useApi<Cluster[]>('/clusters')
  const query = useApi<{ items: Node[]; total: number; page: number; page_size: number }>(`/nodes?${params({ q: search, role, cluster_id: cluster, is_seed: seed, page, page_size: 20, sort_by: sorting[0]?.id ?? 'priority_score', sort_dir: sorting[0]?.desc ? 'desc' : 'asc' })}`)
  const columns = useMemo(() => [
    column.display({ id: 'rank', header: '#', cell: info => <span className="muted">{String((page - 1) * 20 + info.row.index + 1).padStart(2, '0')}</span> }),
    column.accessor('gid', { header: 'Клиент / gid', cell: info => <div><NodeLink gid={info.getValue()} />{info.row.original.is_seed && <span className="seed-label">seed</span>}</div> }),
    column.accessor('role', { header: 'Предполагаемая роль', enableSorting: false, cell: info => <RoleBadge role={info.getValue()} /> }),
    column.accessor('priority_score', { header: 'Приоритет', cell: info => <Score score={info.getValue()} /> }),
    column.display({ id: 'evidence', header: 'Основания для проверки', cell: info => <span className="table-evidence">{info.row.original.evidence}</span> }),
    column.accessor('cluster_id', { header: 'Кластер', cell: info => <Link className="cluster-chip" to={`/clusters/${info.getValue()}`}>К{info.getValue()}</Link> }),
    column.accessor(n => metric(n, 'in_sum'), { id: 'in_sum', header: 'Входящий поток', cell: info => <span className="nowrap">{money(info.getValue())}</span> }),
    column.display({ id: 'actions', header: '', cell: info => <div className="row-actions"><Link title="Открыть связи" to={`/graph?gid=${info.row.original.gid}`}><Network size={15} /></Link><Link title="Открыть карточку" to={`/nodes/${info.row.original.gid}`}><ChevronRight size={15} /></Link></div> }),
  ], [page])
  const table = useReactTable({ data: query.data?.items ?? [], columns, getCoreRowModel: getCoreRowModel(), manualSorting: true, manualPagination: true, state: { sorting }, onSortingChange: updater => { setSorting(updater); setPage(1) } })
  const reset = () => { setRole(''); setCluster(''); setSeed(''); setQ(''); setUrl({}); setPage(1) }
  return <><PageHeading eyebrow="ПОРЯДОК УГЛУБЛЁННОЙ ПРОВЕРКИ" title="Приоритеты, подкреплённые данными" description="Структурное влияние, денежные потоки и связи с исходной выборкой в одном списке."><ExportButton filename="top_nodes.csv" /></PageHeading>
    <div className="priority-callout"><span className="priority-callout-icon"><SlidersHorizontal size={20} /></span><div><strong>Score помогает выбрать следующий шаг</strong><p>Чем выше показатель, тем больше оснований изучить клиента. Роль и приоритет не устанавливают нарушение.</p></div><Link to="/methodology">Из чего состоит score<ArrowUpRight size={14} /></Link></div>
    <Panel><div className="table-filters"><form className="search-field" onSubmit={e => { e.preventDefault(); setUrl(q.trim() ? { q: q.trim() } : {}); setPage(1) }}><Search size={15} /><input aria-label="Поиск по gid" value={q} onChange={e => setQ(e.target.value)} placeholder="Найти по gid" /><button>Найти</button></form><select aria-label="Фильтр по роли" value={role} onChange={e => { setRole(e.target.value); setPage(1) }}><option value="">Все роли</option>{Object.entries(roles).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><select aria-label="Фильтр по кластеру" value={cluster} onChange={e => { setCluster(e.target.value); setPage(1) }}><option value="">Все кластеры</option>{clusters.data?.map(c => <option key={c.cluster_id} value={c.cluster_id}>Кластер {c.cluster_id}</option>)}</select><select aria-label="Фильтр seed" value={seed} onChange={e => { setSeed(e.target.value); setPage(1) }}><option value="">Все клиенты</option><option value="true">Только seed</option><option value="false">Без seed</option></select>{(role || cluster || seed || search) && <button className="icon-button" title="Сбросить фильтры" onClick={reset}><X size={16} /></button>}</div>
      <State loading={query.isLoading} error={query.error} empty={query.data?.total === 0}><div className="table-wrap"><table className="data-table priorities-table"><thead>{table.getHeaderGroups().map(group => <tr key={group.id}>{group.headers.map(header => <th key={header.id}>{header.column.getCanSort() ? <button className="sort-button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{header.column.getIsSorted() === 'desc' ? <ArrowDown size={12} /> : header.column.getIsSorted() === 'asc' ? <ArrowUp size={12} /> : <ArrowUpDown size={12} />}</button> : flexRender(header.column.columnDef.header, header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id}>{row.getVisibleCells().map(cell => <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div></State>
      <div className="pagination"><span>Показано {query.data?.total ? (page - 1) * 20 + 1 : 0}–{Math.min(page * 20, query.data?.total ?? 0)} из {num(query.data?.total)} клиентов</span><div><button className="icon-button" title="Предыдущая страница" disabled={page === 1} onClick={() => setPage(p => p - 1)}><ChevronLeft size={16} /></button><span>Страница {page} / {Math.max(1, Math.ceil((query.data?.total ?? 0) / 20))}</span><button className="icon-button" title="Следующая страница" disabled={page * 20 >= (query.data?.total ?? 0)} onClick={() => setPage(p => p + 1)}><ChevronRight size={16} /></button></div></div>
    </Panel></>
}

export function NodePage() {
  const { gid } = useParams()
  const navigate = useNavigate()
  const query = useApi<Node>(`/nodes/${gid}`)
  const ego = useApi<Graph>(`/nodes/${gid}/ego?depth=1&direction=both`)
  const node = query.data
  const [showRoleScores, setShowRoleScores] = useState(false)
  const evidence = node ? (Array.isArray(node.detailed_evidence) ? node.detailed_evidence : [node.detailed_evidence]) : []
  const ratio = (key: string) => node?.metrics[key] == null ? 'н/д' : pct(Number(node.metrics[key]))
  return <><Link className="back-link" to="/priorities"><ArrowLeft size={14} />К приоритетным клиентам</Link><State loading={query.isLoading} error={query.error}>{node && <>
    <PageHeading eyebrow="ПРОФИЛЬ НАБЛЮДАЕМОГО УЗЛА" title={`Клиент · gid ${node.gid}`} description={`Глубина ${node.depth} · Компонента ${node.metrics.component_id ?? '—'} · ${node.is_seed ? 'Входит в исходную seed-выборку' : 'Обнаружен в наблюдаемой сети'}`}><Link className="button secondary" to={`/copilot?gid=${node.gid}`}><Sparkles size={15} />Обсудить с Copilot</Link><Link className="button primary" to={`/graph?gid=${node.gid}`}><Network size={15} />Раскрыть связи</Link></PageHeading>
    <div className="node-intro"><Panel className="node-summary"><div className="between"><RoleBadge role={node.role} /><span className="confidence">Выраженность роли {pct(node.role_score)}</span></div><h2>Что видно в данных</h2>{evidence.map((text, i) => <p key={i}>{text}</p>)}<div className="node-tags"><Link className="cluster-chip" to={`/clusters/${node.cluster_id}`}><GitBranch size={12} />Кластер {node.cluster_id}</Link>{node.is_seed && <span className="seed-tag">Seed-клиент</span>}{Boolean(node.metrics.boundary_censored) && <span className="boundary-tag">Граница наблюдения</span>}</div></Panel><Panel className="priority-summary"><span className="eyebrow">ПРИОРИТЕТ ПРОВЕРКИ</span><Score score={node.priority_score} large /><p>Порядок аналитического внимания на основе наблюдаемых признаков.</p><Link to="/methodology">Как рассчитан показатель<ArrowUpRight size={13} /></Link></Panel></div>
    <div className="node-metrics"><MetricCard icon={<ArrowDownLeft size={17} />} label="Входящий поток" value={money(metric(node, 'in_sum'))} sub={`${num(metric(node, 'in_degree'))} уникальных отправителей`} /><MetricCard icon={<ArrowUpRight size={17} />} label="Исходящий поток" value={money(metric(node, 'out_sum'))} sub={`${num(metric(node, 'out_degree'))} уникальных получателей`} /><MetricCard icon={<Network size={17} />} label="Связанные seed" value={num(metric(node, 'linked_seed_count'))} sub={`${num(metric(node, 'reachable_seed_count'))} достижимых seed`} /><MetricCard icon={<Clock3 size={17} />} label="Быстрый транзит" value={ratio('rapid_transit_share')} sub="Наблюдаемая доля в пределах 2 дней" /></div>
    <div className="node-analysis-grid"><Panel title="Почему этот клиент в приоритете" subtitle={`Вклад = вес × значение × Q; полнота наблюдения Q = ${metric(node, 'observation_quality').toFixed(2)}`}><div className="factor-list">{node.priority_factors.map(f => <div className="factor-row" key={f.key}><div><span>{f.label}</span><b>{f.contribution.toFixed(3)}</b></div><div className="factor-track"><i style={{ width: `${Math.min(100, Math.abs(f.contribution) / Math.max(...node.priority_factors.map(x => Math.abs(x.contribution)), 0.01) * 100)}%`, background: f.contribution < 0 ? '#eab871' : undefined }} /></div><small>Вес {f.weight.toFixed(2)} · значение {f.value.toFixed(3)}</small></div>)}</div></Panel>
    <Panel title="Ближайшее окружение" subtitle="Прямые входящие и исходящие связи" action={<Link className="panel-link" to={`/graph?gid=${node.gid}`}>Раскрыть<ArrowUpRight size={13} /></Link>}><State loading={ego.isLoading} error={ego.error}><GraphCanvas graph={ego.data} height={340} mini onNode={id => navigate(`/nodes/${id}`)} /></State><div className="neighbor-links">{ego.data?.nodes.filter(n => n.gid !== node.gid).slice(0, 10).map(n => <NodeLink gid={n.gid} key={n.gid} />)}{ego.data?.nodes.length === 1 && <p className="muted">У этого клиента нет наблюдаемых связей.</p>}</div></Panel></div>
    <div className="node-analysis-grid"><Panel title="Дополнительные показатели" subtitle="Описывают только доступную часть операций"><div className="metric-list"><MetricRow label="Средняя / медианная операция" value={`${money(metric(node, 'avg_amount'))} / ${money(metric(node, 'median_amount'))}`} /><MetricRow label="Входящие / исходящие транзакции" value={`${num(metric(node, 'in_tx'))} / ${num(metric(node, 'out_tx'))}`} /><MetricRow label="Доля средств, прошедших дальше" value={ratio('pass_through')} /><MetricRow label="Наблюдаемое удержание (proxy)" value={ratio('retention_proxy')} /><MetricRow label="PageRank / посредничество" value={`${metric(node, 'pagerank').toFixed(5)} / ${metric(node, 'betweenness').toFixed(5)}`} /><MetricRow label="Межкластерное посредничество" value={metric(node, 'intercluster_bridge').toFixed(3)} /><MetricRow label="Активных дней / участие в цикле" value={`${num(metric(node, 'active_days'))} / ${node.metrics.in_cycle ? 'Да' : 'Нет'}`} /><MetricRow label="Концентрация контрагентов" value={ratio('counterparty_concentration')} /></div><button className="method-link role-score-toggle" onClick={() => setShowRoleScores(v => !v)}>Сравнить оценки всех ролей<ChevronRight size={14} /></button>{showRoleScores && <div className="role-score-list">{Object.entries(node.role_scores).sort(([, a], [, b]) => b - a).map(([role, value]) => <div key={role}><RoleBadge role={role as Node['role']} /><span>{value.toFixed(3)}</span></div>)}</div>}</Panel><div className="node-cautions"><Panel title="Ограничения интерпретации"><div className="limitations-list">{node.limitations.length ? node.limitations.map((limitation, i) => <p key={i}><ShieldAlert size={16} />{limitation}</p>) : <p><CircleHelp size={16} />Полный баланс и операции за пределами банка неизвестны.</p>}</div></Panel><Panel className="next-step"><span className="eyebrow">СЛЕДУЮЩИЙ ШАГ</span><h3>Проверить гипотезу</h3><p>{node.next_step}</p><Link to={`/copilot?gid=${node.gid}&question=${encodeURIComponent(`Каких данных не хватает для проверки gid ${node.gid}?`)}`}>Сформулировать запрос данных<ArrowRight size={14} /></Link></Panel></div></div>
  </>}</State></>
}
function MetricCard({ icon, label, value, sub }: { icon: React.ReactNode; label: string; value: string; sub: string }) { return <div className="metric-card"><div>{icon}<span>{label}</span></div><strong>{value}</strong><p>{sub}</p></div> }
function MetricRow({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div> }

export function MethodologyPage() {
  const query = useApi<Methodology>('/methodology')
  const data = query.data
  return <><PageHeading eyebrow="ПРОЗРАЧНАЯ АНАЛИТИКА" title="Методология и границы выводов" description="Каждая роль и каждый приоритет воспроизводимы и объясняются наблюдаемыми признаками." /><State loading={query.isLoading} error={query.error}>{data && <>
    <div className="methodology-banner"><ShieldAlert size={25} /><div><h2>Аналитическая гипотеза требует проверки</h2><p>Система не устанавливает виновность. Оценки отражают силу структурных признаков в ограниченном наборе операций, а не вероятность преступления.</p></div></div>
    <Panel title="Как данные становятся объяснениями" subtitle="Один воспроизводимый pipeline"><div className="pipeline-steps">{['Parquet', 'Валидация', 'Признаки', 'Кластеры', 'Роли', 'Приоритет', 'Объяснения'].map((step, index) => <div key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < 6 && <ChevronRight size={14} />}</div>)}</div></Panel>
    <div className="methodology-roles">{data.roles.map(item => <Panel key={item.role}><RoleBadge role={item.role} /><p>{item.description}</p></Panel>)}</div>
    <div className="methodology-grid"><Panel title="Из чего состоит приоритет" subtitle="Q — коэффициент полноты наблюдения; компоненты нормализованы"><div className="formula">priority = Q × Σ (вес × признак)</div><div className="metric-list">{Object.entries(data.priority_weights).map(([key, value]) => <MetricRow key={key} label={weightLabels[key] ?? key} value={String(value)} />)}</div><p className="method-body">{data.normalization}</p></Panel><Panel title="Кластеризация и правила ролей"><div className="method-body"><p>{data.clustering}</p><p>Основная роль определяется максимальной оценкой из шести ролей. Оценки и правила разрешения равенства заданы в конфигурации аналитики.</p><p>Выраженность роли учитывает силу признаков и разницу с альтернативной ролью. Клиенты на четвёртом колене без исходящих связей не становятся автоматически конечными получателями.</p><p>Отношение исходящего и входящего потоков для seed ограничено неполнотой выборки. Сумма исходящих переводов может превышать входящую.</p></div></Panel></div>
    <Panel title="Обязательные ограничения данных" subtitle="Эти условия влияют на интерпретацию всех результатов"><div className="method-limitations">{data.limitations.map((text, index) => <div key={index}><span>{String(index + 1).padStart(2, '0')}</span><p>{text}</p></div>)}</div></Panel><Panel title="Словарь терминов" action={<BookOpen size={17} />}><div className="glossary">{Object.entries(data.glossary).map(([term, definition]) => <div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</div></Panel>
  </>}</State></>
}
const weightLabels: Record<string, string> = { role: 'Роль и выраженность', seed: 'Связанные seed', centrality: 'Центральность', turnover: 'Оборот', fan: 'Fan-in / fan-out', bridge: 'Межкластерное посредничество', cycle: 'Циклы и возвраты', temporal: 'Быстрый транзит', quality: 'Полнота наблюдений', role_strength: 'Выраженность роли', seed_links: 'Связи с seed', volume: 'Объём переводов', branching: 'Разветвлённость', intercluster: 'Межкластерные связи', cycles: 'Участие в циклах', rapid_transit: 'Быстрый транзит' }


